Disable clang-format

diff --git a/.github/workflows/berkeley-cluster-tests-1.yml b/.github/workflows/berkeley-cluster-tests-1.yml
--- a/.github/workflows/berkeley-cluster-tests-1.yml
+++ b/.github/workflows/berkeley-cluster-tests-1.yml
@@ -163,27 +163,28 @@ jobs:
     if: needs.filter-jobs-on-changes.outputs.run-cpp-lint == 'true'
     steps:
       - uses: actions/checkout@v4
-      # Run 'clang-format', comparing against the base commit hash.
-      # If anything got reformatted, fail and output a patch.
-      # Ensure you are using 'git' coming from conda to get 'clang-format'.
-      - name: Run clang-format
-        run: |
-          cd ${{ env.REMOTE_WORK_DIR }}
-          source sourceme-manager.sh --skip-ssh-setup
-          cd ${{ github.workspace }}
-          git fetch --recurse-submodules=no origin ${{ github.base_ref }}
-          DIFF_COMMIT=$(git rev-parse origin/${{ github.base_ref }})
-          git clang-format $DIFF_COMMIT
-          git diff --ignore-submodules > clang-format.patch
-          if [ -s clang-format.patch ]; then
-            echo "error: clang-format had to fix the following files:"
-            git diff --ignore-submodules --name-only
-            echo "----- 8< ---- PATCH ----- 8< ----"
-            cat clang-format.patch
-            echo "----- 8< ---- PATCH ----- 8< ----"
-            git checkout .
-            exit 1
-          fi
+      # TODO: disabled for now. clang-format error's with no modifications
+      ## Run 'clang-format', comparing against the base commit hash.
+      ## If anything got reformatted, fail and output a patch.
+      ## Ensure you are using 'git' coming from conda to get 'clang-format'.
+      #- name: Run clang-format
+      #  run: |
+      #    cd ${{ env.REMOTE_WORK_DIR }}
+      #    source sourceme-manager.sh --skip-ssh-setup
+      #    cd ${{ github.workspace }}
+      #    git fetch --recurse-submodules=no origin ${{ github.base_ref }}
+      #    DIFF_COMMIT=$(git rev-parse origin/${{ github.base_ref }})
+      #    git clang-format $DIFF_COMMIT
+      #    git diff --ignore-submodules > clang-format.patch
+      #    if [ -s clang-format.patch ]; then
+      #      echo "error: clang-format had to fix the following files:"
+      #      git diff --ignore-submodules --name-only
+      #      echo "----- 8< ---- PATCH ----- 8< ----"
+      #      cat clang-format.patch
+      #      echo "----- 8< ---- PATCH ----- 8< ----"
+      #      git checkout .
+      #      exit 1
+      #    fi
       # TODO: disabled for now. clang-tidy is throwing alot of false positives
       ## Run clang-tidy on the entire codebase. Error will be logged.
       #- name: Run clang-tidy
